SELECT COUNT(*) AS Total_Records FROM ecommerce;
SELECT * FROM ecommerce WHERE order_id IS NULL OR customer_id IS NULL OR total_amount IS NULL;
SELECT DISTINCT category FROM ecommerce;
SELECT DISTINCT region FROM ecommerce;
SELECT DISTINCT payment_method FROM ecommerce;
SELECT ROUND(SUM(total_amount),2) AS Total_Revenue FROM ecommerce;
SELECT COUNT(order_id) AS Total_Orders FROM ecommerce;
SELECT COUNT(DISTINCT customer_id) AS Total_Customers FROM ecommerce;
SELECT SUM(quantity) AS Total_Units_Sold FROM ecommerce;
SELECT ROUND(AVG(total_amount),2) AS Avg_Order_Value FROM ecommerce;
SELECT ROUND(SUM(profit_margin),2) AS Total_Profit FROM ecommerce;
SELECT category, ROUND(SUM(total_amount),2) AS Revenue FROM ecommerce GROUP BY category ORDER BY Revenue DESC;
SELECT region, ROUND(SUM(total_amount),2) AS Revenue FROM ecommerce GROUP BY region ORDER BY Revenue DESC;
SELECT payment_method, ROUND(SUM(total_amount),2) AS Revenue FROM ecommerce GROUP BY payment_method ORDER BY Revenue DESC;
SELECT strftime('%Y-%m', order_date) AS Month, ROUND(SUM(total_amount),2) AS Revenue FROM ecommerce GROUP BY Month ORDER BY Month;
SELECT strftime('%Y-%m', order_date) AS Month, COUNT(order_id) AS Orders FROM ecommerce GROUP BY Month ORDER BY Month;
SELECT product_id, ROUND(SUM(total_amount),2) AS Revenue FROM ecommerce GROUP BY product_id ORDER BY Revenue DESC LIMIT 10;
SELECT category, SUM(quantity) AS Quantity_Sold FROM ecommerce GROUP BY category ORDER BY Quantity_Sold DESC;
SELECT customer_id, ROUND(SUM(total_amount),2) AS Revenue FROM ecommerce GROUP BY customer_id ORDER BY Revenue DESC LIMIT 10;
SELECT customer_gender, ROUND(SUM(total_amount),2) AS Revenue FROM ecommerce GROUP BY customer_gender;
SELECT customer_age, ROUND(SUM(total_amount),2) AS Revenue FROM ecommerce GROUP BY customer_age ORDER BY customer_age;
SELECT returned, COUNT(*) AS Orders FROM ecommerce GROUP BY returned;
SELECT returned, ROUND(SUM(total_amount),2) AS Revenue FROM ecommerce GROUP BY returned;
SELECT region, ROUND(AVG(delivery_time_days),2) AS Avg_Delivery_Days FROM ecommerce GROUP BY region ORDER BY Avg_Delivery_Days DESC;
SELECT region, ROUND(SUM(shipping_cost),2) AS Shipping_Cost FROM ecommerce GROUP BY region ORDER BY Shipping_Cost DESC;
SELECT category, ROUND(SUM(profit_margin),2) AS Profit FROM ecommerce GROUP BY category ORDER BY Profit DESC;
SELECT region, ROUND(SUM(profit_margin),2) AS Profit FROM ecommerce GROUP BY region ORDER BY Profit DESC;
SELECT discount, ROUND(AVG(profit_margin),2) AS Avg_Profit FROM ecommerce GROUP BY discount ORDER BY discount;
SELECT region, ROUND(SUM(total_amount),2) AS Revenue FROM ecommerce GROUP BY region ORDER BY Revenue DESC LIMIT 1;
SELECT category, SUM(quantity) AS Quantity FROM ecommerce GROUP BY category ORDER BY Quantity DESC LIMIT 1;
SELECT category, ROUND(SUM(profit_margin),2) AS Profit FROM ecommerce GROUP BY category ORDER BY Profit DESC LIMIT 1; 
